language: node_js
sudo: required
env:
  global:
  - secure: Hg2KIEhKqOw0J8ZW2C3Pdgp5N4HD/f9jhdluH0tiYRCU4I/jf5grQuA3ohqsbqnJKV5l06gWVIDCdxBDwDEH0h8v9uUG5z/i2diiuLQc94SLQu8kWKkUPDOx+pUyXmfRKj6KnaRTotTLFrwlyuKDi9OfGjQbLZWTvmJUWoFwh4g=
  - secure: U6/Hp/V0ezT/yxeP2bv4S99LSLScKEaOfYwQUbe0+v5dPbN5XZaCUS6iSbNP2K8Mtb1UQUEyL8uN6Zn+khFlJ8/KJshppJ6HJi235CykahBhh9/Cv7EapgDUoss14ntE8EKpm6Ijo4LvVyPVmhgqKk9wP5ykDFtvhoKD4C3guVU=
  - secure: hbc+kcO/tfHSMcJOTp4Wa50cOGzy9NQjD2zdLSwWrzMoDrLh89xWRd9RVe18HlwDnFtDb0gjlDvNp/cXl8dOdqBhbB3OKeoLt0b4zggLdS2ODnv/RtDVeinc8w6biPE24Z9IygtQ4lK9q5jjp/hEYFODl2khr3fy18+qWLsczxvTg6chA8MTjgRLNHHnLWnHiVzNQYgjdCeVRhP9TbIdwTLXjnMB4OhQip//xDAIo/KsDXZsjEnrCuGdmtWjBtQfsFboWErM6sgqLzQuXvkyjE5ANrs4v/UmC8z8FUjq9qvIAI+XGKUMuKguwYD3PbhWtMnSflVmH7bUx32yDmQVkpbjCoJ17Swxmc1FlxfakUQQQzrc7805q7gx2q3ZkRYeQ5HmgnE97uRln2D0ro0PKpMRZJCRAbtEWMt+YQjSRVttIt8ewwBYNHVTEFA4C89xIAUdn/2Gf/DAWYv00mqmRmLf4ATJNE2CVfvj3hree9J/lIR+PM4hKeLJBu7wFGBVGbvyEWH0upDVXnIPyjKTnekCM5miqza1MUz0t79RM071fHsxwUvH+EOQmbg1CQb2MloHKefjlVXv4Dbjbq2r17cSDdBNxoiIsb72ndqQJAdi+Ss6z442HpNzDijm8G9mQ25npZ/VOtOQwmmYXc9OmriAuzyHZ9mx7P/enWP4iDM=
  - secure: CFLaCdWlAOcjgtRazeQEVoxHKo9xeczGtwTQXmAka88xRxz5zdHyy1XlOl3n5f3O+5UrdVGw1KVDnItYR25rTybGe8LMi5+kdPXFi+sIvSER0LRyvdNjVwwUEQmQqwQsxrgTm4Qes5KgSDRV/coLriIKWHz5hjrSDyzJJ2huqo97SDeGmLhLxN1I1H6cAlz9ay2B2BOZZIXKSSGJW53Gw5wpa3tyQMrAqzwoALSGKKqOoE8t9sss6SOTYZ1z3WD92eHRRcGs3SU45IguZfx20g3vkgn9U2WTD+ERetuBgKYUoGnlmUVbChJ/JDhpnkjVwK5C0w9jB6u6jqmL+ZjAFpj3dGNtLtu7LeovTgleSbXlbQda+lMU5InuB/rENRkmgGqZBSXh5nbAcwDu0lX2YkNrhJiPFLSYZENCG0Yj3y8jgKnR0U9mR6WL0YLWmvfaBXfA0gijYVqMY7MxVrTqgcB+YORvflBGliB0deb8Dg5Xz2WpYwSLbQd04svVJM3p8OxJsqC4TauO5JKbu6y9pxxRh2aO/SH/FAFnyDpSm+/FWcTwliMxAsJUqrPFaATj+VYPRUSdMxbBW8cJRWH0FunijLPlKNbApHLGHH+MrxsWfBHj1y26VJzg0Xoavgjfvffq7BlYpBb2CjYMALqYlE9GElrLWPG4Y2x9cBk9R2Y=
node_js: node
addons:
  firefox: latest
  chrome: stable
script:
- xvfb-run npm test
dist: trusty
cache:
  directories:
    - node_modules
